In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
flights = sns.load_dataset('flights')

In [6]:
df = flights

In [7]:
df.head(1)

   year month  passengers
0  1949   Jan         112

In [8]:
df.tail()

     year month  passengers
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        144 non-null    int64
 1   month       144 non-null    category
 2   passengers  144 non-null    int64
dtypes: category(1), int64(2)
memory usage: 2.9 KB

In [10]:
df.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

In [16]:
df.min(numeric_only=True)

year          1949
passengers     104
dtype: int64

In [17]:
df.max(numeric_only = True)

year          1960
passengers     622
dtype: int64

In [18]:
df.mean(numeric_only = True)

year          1954.500000
passengers     280.298611
dtype: float64

In [36]:
df.median(numeric_only = True)

year          1954.5
passengers     265.5
dtype: float64

In [37]:
df.mode(numeric_only = True)

    year  passengers
0   1949       229.0
1   1950         NaN
2   1951         NaN
3   1952         NaN
4   1953         NaN
5   1954         NaN
6   1955         NaN
7   1956         NaN
8   1957         NaN
9   1958         NaN
10  1959         NaN
11  1960         NaN

In [39]:
df.mode()

    year month  passengers
0   1949   Jan       229.0
1   1950   Feb         NaN
2   1951   Mar         NaN
3   1952   Apr         NaN
4   1953   May         NaN
5   1954   Jun         NaN
6   1955   Jul         NaN
7   1956   Aug         NaN
8   1957   Sep         NaN
9   1958   Oct         NaN
10  1959   Nov         NaN
11  1960   Dec         NaN

In [38]:
df.std(numeric_only = True)

year            3.464102
passengers    119.966317
dtype: float64

In [19]:
df.dtypes

year             int64
month         category
passengers       int64
dtype: object

In [20]:
df.shape

(144, 3)

In [21]:
df.index

RangeIndex(start=0, stop=144, step=1)

In [22]:
df.columns

Index(['year', 'month', 'passengers'], dtype='object')

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X = df.iloc[:, 0]    # row, col
X

0      1949
1      1949
2      1949
3      1949
4      1949
       ...
139    1960
140    1960
141    1960
142    1960
143    1960
Name: year, Length: 144, dtype: int64

In [42]:
y = df.iloc[:, -1]
y

0      112
1      118
2      132
3      129
4      121
      ...
139    606
140    508
141    461
142    390
143    432
Name: passengers, Length: 144, dtype: int64

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

In [44]:
X_train.shape

(108,)

In [45]:
X_test.shape

(36,)

In [46]:
y_train.shape, y_test.shape

((108,), (36,))

In [47]:
from sklearn.model_selection import KFold

In [48]:
kf = KFold(n_splits=5,shuffle=True, random_state=42)

In [49]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [51]:
for train_index, test_index in kf.split(X):
    print("Train Index:", train_index)
    print("="*50)
    print("Test Index:", test_index)

Train Index: [  0   1   2   3   5   6   7   8  10  13  14  15  16  17  20  21  22  23
  24  25  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
  44  46  47  48  49  50  52  53  54  57  58  59  60  61  62  63  67  68
  70  71  72  74  75  76  77  79  80  81  83  84  85  86  87  88  89  90
  91  92  93  95  96  98  99 101 102 103 104 105 106 107 108 109 111 112
 114 115 116 118 120 121 122 123 124 126 127 128 129 130 131 134 135 136
 137 138 139 140 141 142 143]
==================================================
Test Index: [  4   9  11  12  18  19  26  27  45  51  55  56  64  65  66  69  73  78
  82  94  97 100 110 113 117 119 125 132 133]
Train Index: [  1   2   3   4   5   6   7   8   9  11  12  13  14  17  18  19  20  21
  26  27  29  30  32  33  34  35  37  38  41  43  45  46  47  48  49  50
  51  52  53  54  55  56  57  58  59  61  62  63  64  65  66  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  85  87  88  89  90  91
  92  94  97  99 100 101 102 103 104 105 106 107 108 109 110 112 113 114
 116 117 119 120 121 122 123 125 126 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143]
==================================================
Test Index: [  0  10  15  16  22  23  24  25  28  31  36  39  40  42  44  60  67  68
  84  86  93  95  96  98 111 115 118 124 127]
Train Index: [  0   1   2   3   4   6   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  31  32  36  37  38  39  40  41
  42  44  45  46  48  50  51  52  54  55  56  57  58  59  60  61  63  64
  65  66  67  68  69  71  72  73  74  75  78  79  82  84  86  87  88  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 110 111 113 114 115 116 117 118 119 120 121 122 124 125 126 127 128 130
 132 133 134 136 138 141 143]
==================================================
Test Index: [  5   7  30  33  34  35  43  47  49  53  62  70  76  77  80  81  83  85
  89 109 112 123 129 131 135 137 139 140 142]
Train Index: [  0   1   4   5   7   9  10  11  12  14  15  16  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  39  40  42  43
  44  45  47  49  51  52  53  55  56  57  59  60  62  63  64  65  66  67
  68  69  70  71  73  74  75  76  77  78  80  81  82  83  84  85  86  87
  89  92  93  94  95  96  97  98  99 100 102 103 106 107 109 110 111 112
 113 115 116 117 118 119 121 123 124 125 127 128 129 130 131 132 133 134
 135 137 138 139 140 142 143]
==================================================
Test Index: [  2   3   6   8  13  17  38  41  46  48  50  54  58  61  72  79  88  90
  91 101 104 105 108 114 120 122 126 136 141]
Train Index: [  0   2   3   4   5   6   7   8   9  10  11  12  13  15  16  17  18  19
  22  23  24  25  26  27  28  30  31  33  34  35  36  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  53  54  55  56  58  60  61  62  64
  65  66  67  68  69  70  72  73  76  77  78  79  80  81  82  83  84  85
  86  88  89  90  91  93  94  95  96  97  98 100 101 104 105 108 109 110
 111 112 113 114 115 117 118 119 120 122 123 124 125 126 127 129 131 132
 133 135 136 137 139 140 141 142]
==================================================
Test Index: [  1  14  20  21  29  32  37  52  57  59  63  71  74  75  87  92  99 102
 103 106 107 116 121 128 130 134 138 143]