# Feature Selection Techniques :-
### 1. Backward Elimination (Using MLXTEND) 
### 2. Forward Elimination (Using MLXTEND)

In [1]:
# Feature Selection Techniques
# Model ke liye important features select karna aur useless hata dena

# 1. Forward Elimination :- 
# 👉 Start with zero features

# 👉 Phir:
# ek-ek karke features add karte hain
# jo model performance improve kare

# 🔁 Steps
# Start: ❌ no features
# Har feature ko try karo
# Jo best performance de → add karo
# Repeat until best set mil jaye

# 👉 Empty se start → useful features add karo


# 2. Backward Elimination
# 👉 Start with all features

# 👉 Phir:
# ek-ek karke least useful remove

# 🔁 Steps
# Start: ✅ all features
# Har feature ka impact check karo
# Jo useless hai → remove
# Repeat

# 👉 Sabse start → useless hatao


# | Feature  | Forward                      | Backward                   |
# | -------- | ---------------------------- | -------------------------- |
# | Start    | No features                  | All features               |
# | Process  | Add                          | Remove                     |
# | Speed    | Slow (jab features zyada ho) | Fast (small dataset me)    |
# | Use case | Jab features bahut zyada ho  | Jab features manageable ho |

In [ ]:
# 👉 MLXTEND = Machine Learning Extensions

# 👉 Ye ek Python library hai jo:
# scikit-learn ko extend karti hai (extra tools provide karti hai)

# 🔑 Main Tool
# 🔹 Sequential Feature Selector (SFS)
# 👉 It performs:
# Forward Selection (adds features step by step)
# Backward Elimination (removes features step by step)

# 👉 sklearn basic ML tools deta hai
# 👉 mlxtend → extra advanced utilities deta hai

# 🔹 MLXTEND me kya milta hai?
# Feature Selection (Forward / Backward) ✅
# Frequent Pattern Mining (Apriori)
# Ensemble methods
# Evaluation tools

# 👉 MLXTEND = extra ML tools for feature selection & more

In [87]:
import pandas as pd
import numpy as np
from mlxtend.feature_selection import SequentialFeatureSelector

In [55]:
df = pd.read_csv(r"C:\Users\harsh\Downloads\archive\loan.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [45]:
x = df.iloc[:,:-1]
y = df["LoanAmount"]

In [51]:
print(df["LoanAmount"].isnull().sum())

22

In [59]:
x = df.drop(["LoanAmount", "Loan_ID"], axis=1)

In [57]:
y = df["LoanAmount"].fillna(df["LoanAmount"].mean())

In [60]:
x.shape

(614, 11)

In [61]:
x.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [116]:
from sklearn.linear_model import LinearRegression
from mlxtend.feature_selection import SequentialFeatureSelector

In [118]:
lr = LinearRegression()

In [ ]:
fs = SequentialFeatureSelector(lr, k_features=5, forward=True)   # Forward ke liye forward=True,  Forward ke liye backward=False
# k_features=5 → final me 5 best features select karega

In [121]:
fs.fit(x, y)

SequentialFeatureSelector(estimator=LinearRegression(), k_features=(5, 5),
                          scoring='r2')

In [122]:
fs.feature_names

['ApplicantIncome',
 'CoapplicantIncome',
 'Loan_Amount_Term',
 'Credit_History',
 'Gender_Male',
 'Married_Yes',
 'Dependents_1',
 'Dependents_2',
 'Dependents_3+',
 'Education_Not Graduate',
 'Self_Employed_Yes',
 'Property_Area_Semiurban',
 'Property_Area_Urban',
 'Loan_Status_Y']

In [123]:
fs.k_feature_names_

('ApplicantIncome',
 'CoapplicantIncome',
 'Loan_Amount_Term',
 'Married_Yes',
 'Education_Not Graduate')

In [124]:
fs.k_score_

np.float64(0.3205732083879558)