# Train Test Split in Dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\harsh\Downloads\archive\AI Job Market Dataset.csv")
df

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10340,10341,Data Engineer,Startup,Technology,USA,Onsite,Entry,2,PhD,1,0,1,0,1,76426,4,2023,Low,4
10341,10342,Data Analyst,Medium,Healthcare,Australia,Hybrid,Entry,10,Master,1,1,0,0,1,61233,9,2024,Medium,6
10342,10343,Machine Learning Engineer,Startup,Education,Germany,Hybrid,Entry,4,PhD,0,0,0,1,0,103681,3,2026,Low,4
10343,10344,Data Engineer,MNC,E-commerce,Canada,Hybrid,Mid,5,PhD,1,1,1,0,0,112895,12,2024,High,9
10344,10345,AI Engineer,Startup,Education,Australia,Onsite,Mid,12,PhD,0,1,1,1,1,159570,11,2022,High,3

In [4]:
df.head(3)

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9

In [5]:
input_data = df.iloc[:,:-1]
output_data = df["job_openings"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.25)

In [8]:
x_train

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency
7277,7278,AI Engineer,Enterprise,E-commerce,Germany,Hybrid,Entry,10,Bachelor,1,0,1,0,1,115022,1,2021,Medium
10262,10263,Data Scientist,Startup,Finance,Australia,Hybrid,Mid,8,PhD,1,1,0,0,1,82342,5,2024,Medium
1148,1149,Business Analyst,MNC,E-commerce,UK,Onsite,Senior,10,Master,1,0,1,0,0,136731,4,2025,High
2050,2051,Business Analyst,MNC,Healthcare,USA,Onsite,Senior,13,Bachelor,0,0,0,0,0,124851,3,2025,High
4020,4021,Data Scientist,Enterprise,E-commerce,Germany,Hybrid,Senior,4,PhD,1,0,0,1,1,121950,3,2023,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9864,9865,AI Engineer,Startup,Retail,Canada,Hybrid,Mid,4,Master,1,1,1,1,1,159469,1,2025,High
4072,4073,Data Analyst,Enterprise,Technology,Germany,Hybrid,Mid,3,Master,0,1,1,0,1,96146,4,2023,Low
9678,9679,Data Engineer,Startup,Finance,Germany,Remote,Mid,2,Bachelor,0,0,1,0,0,89439,7,2024,Low
1164,1165,Data Scientist,Medium,Healthcare,Canada,Onsite,Mid,6,PhD,0,0,0,0,1,89815,2,2020,Low
8253,8254,Data Scientist,Medium,Technology,Germany,Remote,Senior,14,Master,1,1,1,1,0,131461,8,2025,High

In [9]:
x_test

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency
9355,9356,Data Analyst,MNC,Finance,Canada,Onsite,Entry,12,Master,0,1,1,0,0,84216,2,2022,Medium
6008,6009,Business Analyst,Medium,Finance,Singapore,Remote,Mid,5,PhD,1,0,0,1,0,89347,6,2020,Low
5153,5154,Data Scientist,Medium,Technology,UK,Onsite,Senior,0,PhD,0,0,1,0,0,118243,10,2023,Low
6317,6318,Data Analyst,Startup,Healthcare,Canada,Remote,Entry,9,Master,1,0,1,1,0,78250,1,2025,High
7185,7186,Data Scientist,Startup,Finance,Germany,Hybrid,Mid,0,Master,1,1,0,1,1,98698,7,2022,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7308,7309,Machine Learning Engineer,MNC,E-commerce,Singapore,Onsite,Mid,0,Master,1,1,0,1,1,158460,6,2026,Low
6040,6041,Data Engineer,Startup,Education,India,Hybrid,Mid,2,Master,1,0,1,1,0,103666,2,2021,High
1572,1573,Machine Learning Engineer,Enterprise,E-commerce,Germany,Remote,Entry,0,Master,0,1,0,0,1,97226,2,2024,High
282,283,Data Engineer,Startup,E-commerce,Germany,Onsite,Senior,14,Master,1,1,1,1,0,128240,5,2024,High
7991,7992,Data Scientist,Medium,Healthcare,India,Hybrid,Entry,3,Master,0,0,0,1,0,64839,8,2021,Low

In [10]:
y_train

7277     3
10262    1
1148     7
2050     9
4020     5
        ..
9864     8
4072     3
9678     3
1164     4
8253     4
Name: job_openings, Length: 7758, dtype: int64

In [11]:
y_test

9355    1
6008    4
5153    1
6317    8
7185    1
       ..
7308    1
6040    9
1572    7
282     4
7991    2
Name: job_openings, Length: 2587, dtype: int64

In [12]:
x_train.shape

(7758, 18)

In [13]:
x_test.shape

(2587, 18)

In [14]:
y_train.shape

(7758,)

In [15]:
y_test.shape

(2587,)