In [1]:
import pandas as pd

# Woking with JSON

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.0386
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.6670
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.8630
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,3.8800
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,2.5100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.1720
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.1920
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-02,1780358402,0.2820

# Working with SQL

In [4]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\harsh\desktop\saloni\ml\.venv\lib\site-packages (2.2.9)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'c:\Users\harsh\Desktop\Saloni\ml\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [5]:
import mysql.connector

In [6]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [8]:
df = pd.read_sql("SELECT * FROM countrylanguage", conn)

C:\Users\harsh\AppData\Local\Temp\ipykernel_24384\4122591791.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM countrylanguage", conn)

In [9]:
df

  CountryCode Language IsOfficial  Percentage
0         IND    Hindi          T        43.6
1         IND  English          F        12.0
2         USA  English          T        95.0