In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
df.sample(2)

    age  gender   review education purchased
47   38  Female     Good        PG       Yes
5    31  Female  Average    School       Yes

In [6]:
df.review.value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

# 1. OneHotEncoding using Pandas

In [7]:
pd.get_dummies(df, columns=['gender', 'review'])

,age,education,purchased,gender_Female,gender_Male,review_Average,review_Good,review_Poor
0,30,School,No,True,False,True,False,False
1,68,UG,No,True,False,False,False,True
2,70,PG,No,True,False,False,True,False
3,72,PG,No,True,False,False,True,False
4,16,UG,No,True,False,True,False,False
5,31,School,Yes,True,False,True,False,False
6,18,School,No,False,True,False,True,False
7,60,School,Yes,True,False,False,False,True
8,65,UG,No,True,False,True,False,False
9,74,UG,Yes,False,True,False,True,False
10,98,UG,Yes,True,False,False,True,False
11,74,UG,Yes,False,True,False,True,False
12,51,School,No,False,True,False,False,True
13,57,School,No,True,False,True,False,False
14,15,PG,Yes,False,True,False,False,True
15,75,UG,No,False,True,False,False,True
16,59,UG,Yes,False,True,False,False,True
17,22,UG,Yes,True,False,False,False,True
18,19,School,No,False,True,False,True,False
19,97,PG,Yes,False,True,False,False,True
20,57,School,Yes,True,False,True,False,False
21,32,PG,No,False,True,True,False,False
22,18,PG,Yes,True,False,False,False,True
23,96,School,No,True,False,False,True,False
24,16,PG,Yes,True,False,True,False,False
25,57,School,No,True,False,False,True,False
26,53,PG,No,True,False,False,False,True
27,69,PG,No,True,False,False,False,True
28,48,School,No,False,True,False,False,True
29,83,UG,Yes,True,False,True,False,False
30,73,UG,No,False,True,True,False,False
31,22,School,Yes,True,False,False,False,True
32,92,UG,Yes,False,True,True,False,False
33,89,PG,Yes,True,False,False,True,False
34,86,School,No,False,True,True,False,False
35,74,School,Yes,False,True,False,False,True
36,34,UG,Yes,True,False,False,True,False
37,94,PG,Yes,False,True,True,False,False
38,45,School,No,True,False,False,True,False
39,76,PG,No,False,True,False,False,True
40,39,School,No,False,True,False,True,False
41,23,PG,Yes,False,True,False,True,False
42,30,PG,Yes,True,False,False,True,False
43,27,PG,No,False,True,False,False,True
44,77,UG,No,True,False,True,False,False
45,61,PG,Yes,False,True,False,False,True
46,64,PG,No,True,False,False,False,True
47,38,PG,Yes,True,False,False,True,False
48,39,UG,Yes,True,False,False,True,False
49,25,UG,No,True,False,False,True,False

# 2. K-1 OneHotEncoding

In [8]:
pd.get_dummies(df, columns=['review', 'gender'], drop_first=True)

    age education purchased  review_Good  review_Poor  gender_Male
0    30    School        No        False        False        False
1    68        UG        No        False         True        False
2    70        PG        No         True        False        False
3    72        PG        No         True        False        False
4    16        UG        No        False        False        False
5    31    School       Yes        False        False        False
6    18    School        No         True        False         True
7    60    School       Yes        False         True        False
8    65        UG        No        False        False        False
9    74        UG       Yes         True        False         True
10   98        UG       Yes         True        False        False
11   74        UG       Yes         True        False         True
12   51    School        No        False         True         True
13   57    School        No        False        False        False
14   15        PG       Yes        False         True         True
15   75        UG        No        False         True         True
16   59        UG       Yes        False         True         True
17   22        UG       Yes        False         True        False
18   19    School        No         True        False         True
19   97        PG       Yes        False         True         True
20   57    School       Yes        False        False        False
21   32        PG        No        False        False         True
22   18        PG       Yes        False         True        False
23   96    School        No         True        False        False
24   16        PG       Yes        False        False        False
25   57    School        No         True        False        False
26   53        PG        No        False         True        False
27   69        PG        No        False         True        False
28   48    School        No        False         True         True
29   83        UG       Yes        False        False        False
30   73        UG        No        False        False         True
31   22    School       Yes        False         True        False
32   92        UG       Yes        False        False         True
33   89        PG       Yes         True        False        False
34   86    School        No        False        False         True
35   74    School       Yes        False         True         True
36   34        UG       Yes         True        False        False
37   94        PG       Yes        False        False         True
38   45    School        No         True        False        False
39   76        PG        No        False         True         True
40   39    School        No         True        False         True
41   23        PG       Yes         True        False         True
42   30        PG       Yes         True        False        False
43   27        PG        No        False         True         True
44   77        UG        No        False        False        False
45   61        PG       Yes        False         True         True
46   64        PG        No        False         True        False
47   38        PG       Yes         True        False        False
48   39        UG       Yes         True        False        False
49   25        UG        No         True        False        False

# 3. OneHotEncoding using Sklearn

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:,-1], test_size=0.2, random_state=42)

In [12]:
X_train.head()

    age  gender   review education
12   51    Male     Poor    School
4    16  Female  Average        UG
37   94    Male  Average        PG
8    65  Female  Average        UG
3    72  Female     Good        PG

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
# Create One Hot Encoder
# drop='first' removes the first category to avoid dummy variable trap
# sparse_output=False returns a normal NumPy array instead of a sparse matrix
# dtype=np.int32 stores encoded values as integers
ohe = OneHotEncoder(
    drop='first',
    sparse_output=False,
    dtype=np.int32
)

In [21]:
X_train_new = ohe.fit_transform(X_train[['gender']])

In [22]:
X_test_new = ohe.transform(X_test[['gender']])

In [25]:
X_train_new.shape

(40, 1)

In [27]:
np.hstack((X_train[['review', 'gender']].values, X_train_new))

# Combine the selected columns ('review' and 'gender')
# with the One Hot Encoded columns stored in X_train_new.
# np.hstack() joins arrays horizontally (column-wise).

array([['Poor', 'Male', 1],
       ['Average', 'Female', 0],
       ['Average', 'Male', 1],
       ['Average', 'Female', 0],
       ['Good', 'Female', 0],
       ['Good', 'Male', 1],
       ['Good', 'Male', 1],
       ['Poor', 'Female', 0],
       ['Good', 'Female', 0],
       ['Poor', 'Male', 1],
       ['Good', 'Male', 1],
       ['Poor', 'Male', 1],
       ['Average', 'Female', 0],
       ['Average', 'Male', 1],
       ['Poor', 'Female', 0],
       ['Average', 'Female', 0],
       ['Average', 'Female', 0],
       ['Poor', 'Female', 0],
       ['Good', 'Female', 0],
       ['Average', 'Female', 0],
       ['Average', 'Female', 0],
       ['Good', 'Male', 1],
       ['Good', 'Female', 0],
       ['Poor', 'Female', 0],
       ['Average', 'Male', 1],
       ['Good', 'Female', 0],
       ['Poor', 'Male', 1],
       ['Poor', 'Male', 1],
       ['Good', 'Female', 0],
       ['Good', 'Male', 1],
       ['Good', 'Female', 0],
       ['Poor', 'Female', 0],
       ['Good', 'Male', 1],
       ['Good', 'Female', 0],
       ['Average', 'Female', 0],
       ['Poor', 'Female', 0],
       ['Good', 'Female', 0],
       ['Poor', 'Male', 1],
       ['Poor', 'Male', 1],
       ['Good', 'Female', 0]], dtype=object)

# 4. OneHotEncoding with Top Categories

In [28]:
counts = df['gender'].value_counts()

In [29]:
df['gender'].nunique()

2

In [35]:
# Threshold = Limit / Cut-off Value
# Aap decide karte ho ki kis frequency ke niche wali categories ko rare category maana jayega.

threshold = 5       # Jinki frequency 5 ya usse kam hai, unhe rare category maan lo.

repl = counts[counts <= threshold].index    # # Get categories whose count is 5 or less

In [38]:
# Replace rare categories with 'uncommon' (a label used for all low-frequency values)
# Example: if 'Other', 'Unknown', 'NA' occur very few times, they are replaced with 'uncommon'
# Then convert categories into 0/1 columns using one-hot encoding
# Finally, display 5 random rows

pd.get_dummies(df['gender'].replace(repl, 'uncommon')).sample(5)

    Female   Male
43   False   True
30   False   True
46    True  False
0     True  False
10    True  False